server:
  port: 8901

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

eureka:
  instance:
    preferIpAddress: true
    hostname: auth-service
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

jwt:
  secret: 55FA4000E92C1E46A6A5DAF0E7874336
  expiration:
    access: 5
    refresh: 10080