server:
  port: 8902

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

eureka:
  client:
    fetch-registry: true
